title: "PMB Generative Art Page"
description: "This GitHub Page consist of 3 different generated art graphics along with a description of what each art piece represents. 
The website will be a representation of a mini portfolio that is shared amongst Page Powell, Maggie Nguyen and Bailey Stern."
theme: jekyll-theme-cayman

